name: Windows.

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '!docs/building-win.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/win.yml'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'Telegram/build/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/SourceFiles/platform/linux/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.sh'
      - 'Telegram/Telegram.plist'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '!docs/building-win.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/win.yml'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'Telegram/build/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/SourceFiles/platform/linux/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.sh'
      - 'Telegram/Telegram.plist'

jobs:

  windows:
    name: Windows
    runs-on: windows-2022

    strategy:
      matrix:
        arch: [Win32, x64]

    env:
      UPLOAD_ARTIFACT: "false"
      ONLY_CACHE: "false"
      PREPARE_PATH: "Telegram/build/prepare/prepare.py"

    defaults:
      run:
        shell: cmd
        working-directory: ${{ github.workspace }}

    steps:
      - name: Prepare directories.
        run: |
          mkdir %userprofile%\TBuild\Libraries
          echo TBUILD=%userprofile%\TBuild>>%GITHUB_ENV%

      - name: Get repository name.
        shell: bash
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - uses: ilammy/msvc-dev-cmd@v1.10.0
        name: Native Tools Command Prompt.
        with:
          arch: ${{ matrix.arch }}

      - name: Clone.
        uses: LebedevRI/checkout@issue197
        with:
          submodules: recursive
          path: ${{ env.TBUILD }}\${{ env.REPO_NAME }}

      - name: Choco installs.
        run: |
          choco install --no-progress -y nasm strawberryperl yasm jom ninja
          py -m pip install pywin32

      - name: Install msys64.
        run: |
          mkdir %TBUILD%\ThirdParty
          xcopy /E /I C:\msys64 %TBUILD%\ThirdParty\msys64

      - name: Set up environment paths.
        shell: bash
        run: |
          echo "C:\\Strawberry\\perl\\bin\\" >> $GITHUB_PATH
          echo "C:\\Program Files\\NASM\\" >> $GITHUB_PATH
          echo "C:\\ProgramData\\chocolatey\\lib\\ninja\\tools\\" >> $GITHUB_PATH

          echo "Configurate git for cherry-picks."
          git config --global user.email "you@example.com"
          git config --global user.name "Sample"

      - name: First set up.
        run: |
          powershell -c "wget ${{ secrets.PACK_FILE }} -OutFile p.7z"
          copy p.7z %TBUILD%\p.7z

          C:
          cd %TBUILD%\

          mkdir DesktopPrivate
          cd DesktopPrivate

          echo "#pragma once" > alpha_private.h
          echo "#pragma once" > packer_private.h

          echo ${{ secrets.ALPHA_PRIVATE }} >> alpha_private.h
          echo ${{ secrets.PACKER_PRIVATE }} >> packer_private.h

          cd ..

          7z x p.7z -p${{ secrets.PACK_FILE_PASSWORD }}

      - name: NuGet sources.
        run: |
          nuget sources Disable -Name "Microsoft Visual Studio Offline Packages"
          nuget sources Add -Source https://api.nuget.org/v3/index.json & exit 0

      - name: Libraries cache.
        id: cache-libs
        uses: actions/cache@v2
        with:
          path: ${{ env.TBUILD }}/Libraries
          key: ${{ runner.OS }}-libs

      - name: Libraries.
        env:
          GYP_MSVS_OVERRIDE_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\'
          GYP_MSVS_VERSION: 2022
        run: |
          C:
          cd %TBUILD%
          %REPO_NAME%/Telegram/build/prepare/win.bat silent

      - name: Read defines.
        shell: bash
        run: |
          DEFINE=""
          if [ -n "${{ matrix.defines }}" ]; then
            DEFINE="-D ${{ matrix.defines }}=ON"
            echo Define from matrix: $DEFINE
            echo "ARTIFACT_NAME=Telegram_${{ matrix.defines }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=Telegram" >> $GITHUB_ENV
          fi
          echo "TDESKTOP_BUILD_DEFINE=$DEFINE" >> $GITHUB_ENV

      - name: Free up some disk space.
        run: |
          C:
          cd %TBUILD%
          del /S Libraries\*.pdb
          del /S Libraries\*.pch
          del /S Libraries\*.obj

      - name: Telegram Desktop build.
        if: env.ONLY_CACHE == 'false'
        run: |
          C:
          cd %TBUILD%\%REPO_NAME%\Telegram

          call configure.bat ^
          ${{ matrix.arch }} ^
          -D TDESKTOP_API_ID=${{ secrets.API_ID }} ^
          -D TDESKTOP_API_HASH=${{ secrets.API_HASH }} ^
          -D DESKTOP_APP_USE_PACKAGED=OFF ^
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF ^
          -D DESKTOP_APP_NO_PDB=ON ^
          -DCMAKE_CXX_FLAGS=/bigobj ^
          %TDESKTOP_BUILD_DEFINE% ^
          -DCMAKE_SYSTEM_VERSION=%SDK%

          cd ..\out
          msbuild -m Telegram.sln /p:Configuration=Release,Platform=${{ matrix.arch }},DebugSymbols=false,DebugType=none

      - name: Move artifact.
        if: env.UPLOAD_ARTIFACT == 'true'
        run: |
          mkdir artifact
          move %TBUILD%\%REPO_NAME%\out\Release\Telegram.exe artifact/
      - uses: actions/upload-artifact@master
        name: Upload artifact.
        if: env.UPLOAD_ARTIFACT == 'true'
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifact\

      - name: Compress.
        if: (${{ matrix.arch }} == 'x64')
        run: |
          7z a Telegram_x64.zip %TBUILD%\%REPO_NAME%\out\Release\Telegram.exe

      - name: Deploy.
        if: (${{ matrix.arch }} == 'x64')
        run: |
          C:
          cd %TBUILD%\
          call ci_start.bat >nul 2>&1

      - name: Upload.
        if: (github.event_name == 'release' && ${{ matrix.arch }} == 'x64')
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Telegram_x64.zip
          tag: ${{ github.event.release.tag_name }}
          asset_name: Telegram_x64.zip
